import { motion } from 'motion/react';
import { ArrowLeft, Download, FileText, CheckCircle2 } from 'lucide-react';
import { toast } from 'sonner';

interface ExamStructurePreviewProps {
    questions: any[];
    subjectName: string;
    onBack: () => void;
    rubricName?: string;
}

export function ExamStructurePreview({ questions, subjectName, onBack, rubricName }: ExamStructurePreviewProps) {

    // Group questions by type
    const groupedQuestions = {
        'PART A: MULTIPLE CHOICE QUESTIONS': questions.filter(q => q.type === 'MCQ' || q.question_type === 'MCQ'),
        'PART B: SHORT ANSWER QUESTIONS': questions.filter(q => q.type === 'Short' || q.question_type === 'Short'),
        'PART C: ESSAY QUESTIONS': questions.filter(q => q.type === 'Essay' || q.question_type === 'Essay'),
        'PART D: CASE STUDIES': questions.filter(q => q.type === 'Case Study' || q.question_type === 'Case Study'),
    };

    const handleDownload = () => {
        // Physical storage download logic (Save as Text/Doc for maximum compatibility)
        const examText = `
${subjectName.toUpperCase()} - EXAM PAPER
Generated by AI Exam Oracle
--------------------------------------------------
Total Questions: ${questions.length}
Total Marks: ${questions.reduce((acc, q) => acc + (q.marks || 1), 0)}
--------------------------------------------------

QUESTIONS:
${questions.map((q, i) => `
[QUESTION ${i + 1}] (${q.marks || 1} Marks)
${q.question_text || q.question}
${(q.options && q.options.length > 0) ? `Options:\n${q.options.map((opt: string, idx: number) => `  ${String.fromCharCode(65 + idx)}. ${opt}`).join('\n')}` : ''}
`).join('\n')}

--------------------------------------------------
End of Exam Paper
        `;

        const blob = new Blob([examText], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${subjectName.replace(/\s+/g, '_')}_Exam_Paper.txt`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);

        // Also trigger print as backup
        window.print();
        toast.success("Exam Paper saved to device downloads!");
    };

    return (
        <div className="min-h-full pb-32 bg-[#F5F1ED] print:pb-0 print:bg-white">
            {/* Header */}
            <div className="bg-[#0A1F1F] px-6 pt-12 pb-6 rounded-b-[32px] shadow-xl relative overflow-hidden print:hidden">
                <div className="absolute top-0 left-0 w-full h-full bg-[url('https://grainy-gradients.vercel.app/noise.svg')] opacity-20" />

                <div className="relative z-10 flex items-center gap-4 mb-4">
                    <motion.button
                        whileHover={{ scale: 1.1, x: -3 }}
                        whileTap={{ scale: 0.9 }}
                        onClick={onBack}
                        className="w-10 h-10 bg-white/10 rounded-xl flex items-center justify-center backdrop-blur-md border border-white/20 shadow-lg active:scale-90 transition-all"
                    >
                        <ArrowLeft className="w-5 h-5 text-white" />
                    </motion.button>
                    <h1 className="text-xl font-black text-white tracking-tight">Exam Structure</h1>
                </div>

                {/* Summary Card - Compact */}
                <div className="bg-white rounded-xl p-4 flex items-center gap-4 shadow-lg">
                    <div className="w-10 h-10 bg-[#8E61FF]/10 rounded-lg flex items-center justify-center flex-shrink-0">
                        <FileText className="w-5 h-5 text-[#8E61FF]" />
                    </div>
                    <div>
                        <h2 className="text-sm font-bold text-[#0A1F1F] mb-0.5">Structure Preview</h2>
                        <p className="text-[10px] text-[#8B9E9E] font-medium leading-tight">
                            {questions.length} Questions • {subjectName}
                        </p>
                    </div>
                </div>
            </div>

            {/* Print Header (Visible only when printing) */}
            <div className="hidden print:block p-8 border-b-2 border-black mb-6">
                <h1 className="text-2xl font-black text-black mb-2">{subjectName}</h1>
                <p className="text-xs text-gray-600 mb-4">Generated by AI Exam Oracle</p>
                <div className="flex justify-between text-xs border-t pt-2">
                    <span><strong>Duration:</strong> 3 Hours</span>
                    <span><strong>Total Marks:</strong> {questions.reduce((acc, q) => acc + (q.marks || 1), 0)}</span>
                </div>
            </div>

            {/* Content */}
            <div className="px-6 py-8 space-y-8 print:p-8 print:space-y-6">
                {Object.entries(groupedQuestions).map(([sectionTitle, sectionQuestions]) => {
                    if (sectionQuestions.length === 0) return null;

                    return (
                        <div key={sectionTitle} className="break-inside-avoid">
                            <h3 className="text-xs font-black text-[#8E61FF] uppercase tracking-widest mb-4 ml-1 print:text-black print:text-sm print:mb-2">
                                {sectionTitle}
                            </h3>

                            <div className="space-y-4 print:space-y-6">
                                {sectionQuestions.map((q, index) => (
                                    <div
                                        key={q.id || index}
                                        className="bg-white rounded-2xl p-5 shadow-sm border border-[#E5DED6] print:shadow-none print:border-0 print:p-0 print:mb-4 break-inside-avoid"
                                    >
                                        <div className="flex items-start justify-between mb-3 print:mb-1">
                                            <span className="text-[10px] font-bold text-[#8B9E9E] uppercase print:text-black print:text-xs">Question {index + 1}</span>
                                            <div className="px-2 py-1 bg-[#F5F1ED] rounded-lg text-[10px] font-bold text-[#0A1F1F] print:bg-transparent print:p-0 print:text-black">
                                                {q.marks || 1} Marks
                                            </div>
                                        </div>

                                        <p className="text-sm font-bold text-[#0A1F1F] mb-4 leading-relaxed print:text-black print:text-base">
                                            {q.question_text || q.question}
                                        </p>

                                        {/* MCQ Options */}
                                        {(q.type === 'MCQ' || q.question_type === 'MCQ') && (q.options?.length > 0) && (
                                            <div className="space-y-2 mb-4 pl-2 border-l-2 border-[#E5DED6] print:border-l-4 print:border-gray-300">
                                                {q.options.map((opt: string, i: number) => (
                                                    <div key={i} className="text-xs text-[#5C6B6B] print:text-black print:text-sm">
                                                        <span className="font-bold mr-2">{String.fromCharCode(65 + i)}.</span> {opt}
                                                    </div>
                                                ))}
                                            </div>
                                        )}
                                    </div>
                                ))}
                            </div>
                        </div>
                    );
                })}
            </div>

            {/* Floating Download Button */}
            <div className="fixed bottom-6 left-6 right-6 z-50 print:hidden">
                <button
                    onClick={handleDownload}
                    className="w-full bg-[#4F46E5] text-white rounded-2xl py-4 font-bold shadow-2xl flex items-center justify-center gap-3 active:scale-95 transition-transform"
                >
                    <Download className="w-5 h-5" />
                    <div className="flex flex-col items-start leading-none">
                        <span className="text-sm">Print / Save as PDF</span>
                        <span className="text-[10px] opacity-70 font-normal">Select 'Save as PDF' in options</span>
                    </div>
                </button>
            </div>

            <style>{`
        @media print {
          @page { margin: 0; size: auto; }
          body { 
            background: white !important; 
            print-color-adjust: exact; 
            -webkit-print-color-adjust: exact; 
          }
          /* Hide non-print elements globally if needed, assuming tailwind print:hidden works */
        }
      `}</style>
        </div>
    );
}
